freebsd_task:
  name: "FreeBSD (Unit tests only)"
  timeout_in: 20m
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    image: family/freebsd-13-0
    platform: freebsd
    cpu: 2
    memory: 4G
  install_script:
    - pkg install -y go
  test_script:
    - go test -v ./pkg/...
# TODO: run `go test -v ./cmd/...`
# FIXME: `nerdctl run` is broken on FreeBSD: https://github.com/containerd/nerdctl/issues/868

windows_task:
  name: "Windows"
  timeout_in: 20m
  compute_engine_instance:
    image_project: cirrus-images
    image: family/windows-docker-builder
    platform: windows
    cpu: 2
    memory: 4G
  matrix:
    - name: "Windows/containerd-1.6"
      env:
        ctrdVersion: 1.6.4
  env:
    CGO_ENABLED: 0
  build_script:
    - mkdir "C:\Windows\system32\config\systemprofile\AppData\Local\Temp\"
    - powershell hack/configure-windows-ci.ps1
    - refreshenv
    - go install .\cmd\nerdctl\
    - go test -v ./cmd/...
