freebsd_instance:
  image_family: freebsd-13-0

task:
  name: test-freebsd-amd64
  env:
    NERDCTL_RUN_ARGS: --net none knast/freebsd:13-STABLE echo "Nerdctl is up and running."
  install_script:
    - pkg install -y go containerd runj
    - daemon -o containerd.out containerd
  test_script:
    - go test -v ./pkg/...
    - cd cmd/nerdctl
    - sudo go run . run $NERDCTL_RUN_ARGS | grep running
# TODO: run `go test -v ./cmd/...`

docker_builder:
  name: windows
  platform: windows
  os_version: 2019
  matrix:
    - name: Windows 1.5 tests
      env:
        ctrdVersion: 1.5.8
    - name: Windows 1.6 tests
      env:
        ctrdVersion: 1.6.0-beta.3
  env:
    CGO_ENABLED: 0
  build_script:
    - mkdir "C:\Windows\system32\config\systemprofile\AppData\Local\Temp\"
    - powershell hack/configure-windows-ci.ps1
    - refreshenv
    - go install .\cmd\nerdctl\
    - go test -v ./cmd/...
