freebsd_instance:
  image_family: freebsd-13-0

task:
  name: test-freebsd-amd64
  env:
    NERDCTL_RUN_ARGS: --net none knast/freebsd:13-STABLE echo "Nerdctl is up and running."
  install_script:
    - pkg install -y go containerd runj
    - daemon -o containerd.out containerd
  test_script:
    - go test -v ./pkg/...
    - cd cmd/nerdctl
    - sudo go run . run $NERDCTL_RUN_ARGS | grep running

docker_builder:
  name: windows
  platform: windows
  os_version: 2019
  env:
    CGO_ENABLED: 0
  build_script:
    - mkdir "C:\Windows\system32\config\systemprofile\AppData\Local\Temp\"
    - powershell hack/configure-windows-ci.ps1
    - refreshenv
    - go install .\cmd\nerdctl\
    - go test -v -run "^(TestRunWorkdir|TestRunWithDoubleDash|TestRunExitCode|TestRunCIDFile|TestRunEnvFile|TestRunEnv|TestExec|ImageInspect|TestRunUserName)$" ./cmd/...
