name: test

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
        args: --verbose

  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Prepare test environment"
      run: DOCKER_BUILDKIT=1 docker build -t test --target test .
    - name: "Test"
      run: docker run -t --rm --privileged test

  cross:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Cross"
      run: make artifacts

  test-docker-compatibility:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Ensure that the test suite is compatible with Docker"
      run: go test -v -exec sudo -test.target=docker .
